/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upxiii;

import java.sql.*;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JList;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author leogo
 */
public class CadastroLocal extends javax.swing.JFrame {

//    ArrayList<Object> Jarray = new ArrayList();
    ArrayList<String> checkboxitens = new ArrayList();
//    JList<String> lista = new JList();

    /**
     * Creates new form CadastroLocal
     */
    public CadastroLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        check = new javax.swing.ButtonGroup();
        jLabel10 = new javax.swing.JLabel();
        btn_enviar_cadastro = new javax.swing.JButton();
        btn_voltar_cadastro = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfc_nome = new javax.swing.JTextField();
        tfc_email = new javax.swing.JTextField();
        tfc_rua = new javax.swing.JTextField();
        tfc_tel = new javax.swing.JTextField();
        tfc_num = new javax.swing.JTextField();
        tfc_compl = new javax.swing.JTextField();
        tfc_cep = new javax.swing.JTextField();
        tfc_cidade = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cb_cat = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tfc_bairro = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        chkSmart = new javax.swing.JCheckBox();
        chkTablet = new javax.swing.JCheckBox();
        chkPilha = new javax.swing.JCheckBox();
        chkOleo = new javax.swing.JCheckBox();
        chkMed = new javax.swing.JCheckBox();
        chkSofa = new javax.swing.JCheckBox();
        chkMicro = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro para Local de Descarte");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 90, 72));
        jLabel10.setText("Cadastro para Local de Descarte");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(190, 10, 590, 40);

        btn_enviar_cadastro.setBackground(new java.awt.Color(240, 240, 240));
        btn_enviar_cadastro.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_enviar_cadastro.setForeground(new java.awt.Color(122, 122, 122));
        btn_enviar_cadastro.setText("Enviar");
        btn_enviar_cadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        btn_enviar_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_enviar_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_enviar_cadastro);
        btn_enviar_cadastro.setBounds(470, 490, 166, 54);

        btn_voltar_cadastro.setBackground(new java.awt.Color(240, 240, 240));
        btn_voltar_cadastro.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_voltar_cadastro.setForeground(new java.awt.Color(122, 122, 122));
        btn_voltar_cadastro.setText("Voltar");
        btn_voltar_cadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        btn_voltar_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar_cadastro.setMaximumSize(new java.awt.Dimension(74, 32));
        btn_voltar_cadastro.setMinimumSize(new java.awt.Dimension(74, 32));
        btn_voltar_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_cadastro);
        btn_voltar_cadastro.setBounds(220, 490, 170, 50);

        jPanel1.setBackground(new java.awt.Color(237, 250, 234));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(508, 771));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 122, 122));
        jLabel1.setText("Nome");

        jLabel2.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 122, 122));
        jLabel2.setText("Email");

        jLabel3.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 122, 122));
        jLabel3.setText("logradouro");

        jLabel4.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(122, 122, 122));
        jLabel4.setText("Telefone");

        jLabel5.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(122, 122, 122));
        jLabel5.setText("Complemento");

        jLabel6.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(122, 122, 122));
        jLabel6.setText("Número");

        jLabel7.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(122, 122, 122));
        jLabel7.setText("Cidade");

        jLabel8.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(122, 122, 122));
        jLabel8.setText("CEP");

        jLabel9.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 90, 72));
        jLabel9.setText("Dados Pessoais");

        tfc_nome.setForeground(new java.awt.Color(122, 122, 122));
        tfc_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));
        tfc_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfc_nomeActionPerformed(evt);
            }
        });

        tfc_email.setForeground(new java.awt.Color(122, 122, 122));
        tfc_email.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        tfc_rua.setForeground(new java.awt.Color(122, 122, 122));
        tfc_rua.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        tfc_tel.setForeground(new java.awt.Color(122, 122, 122));
        tfc_tel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        tfc_num.setForeground(new java.awt.Color(122, 122, 122));
        tfc_num.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        tfc_compl.setForeground(new java.awt.Color(122, 122, 122));
        tfc_compl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        tfc_cep.setForeground(new java.awt.Color(122, 122, 122));
        tfc_cep.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        tfc_cidade.setForeground(new java.awt.Color(122, 122, 122));
        tfc_cidade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        jLabel14.setFont(new java.awt.Font("Baloo 2", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 90, 72));
        jLabel14.setText("  Materiais Aceitos");

        jLabel15.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(159, 135, 114));
        jLabel15.setText("Filtrar Categoria");

        cb_cat.setFont(new java.awt.Font("Baloo 2", 1, 13)); // NOI18N
        cb_cat.setForeground(new java.awt.Color(102, 90, 72));
        cb_cat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Categoria", "Eletronico", "Pilhas e Baterias", "Vestuario", "Medicamentos", "Móveis", "Óleos", "Plásticos", "Eletrodomésticos" }));
        cb_cat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        cb_cat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cb_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_catActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(122, 122, 122));
        jLabel13.setText("Bairro");

        tfc_bairro.setForeground(new java.awt.Color(122, 122, 122));
        tfc_bairro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        jPanel2.setBackground(new java.awt.Color(237, 250, 234));

        chkSmart.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        chkSmart.setForeground(new java.awt.Color(122, 122, 122));
        chkSmart.setText("SmarthPhone");
        chkSmart.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 123, 123), 1, true));
        chkSmart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkSmart.setName("1"); // NOI18N
        chkSmart.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSmartStateChanged(evt);
            }
        });
        chkSmart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkSmartMouseClicked(evt);
            }
        });
        chkSmart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSmartActionPerformed(evt);
            }
        });

        chkTablet.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        chkTablet.setForeground(new java.awt.Color(122, 122, 122));
        chkTablet.setText("Tablet");
        chkTablet.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 123, 123), 1, true));
        chkTablet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkTablet.setName("2"); // NOI18N
        chkTablet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkTabletStateChanged(evt);
            }
        });
        chkTablet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkTabletMouseClicked(evt);
            }
        });

        chkPilha.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        chkPilha.setForeground(new java.awt.Color(122, 122, 122));
        chkPilha.setText("Pilha");
        chkPilha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 123, 123), 1, true));
        chkPilha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkPilha.setName("3"); // NOI18N
        chkPilha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkPilhaStateChanged(evt);
            }
        });
        chkPilha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkPilhaMouseClicked(evt);
            }
        });

        chkOleo.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        chkOleo.setForeground(new java.awt.Color(122, 122, 122));
        chkOleo.setText("Óleo de Cozinha");
        chkOleo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 123, 123), 1, true));
        chkOleo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkOleo.setName("6"); // NOI18N
        chkOleo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkOleoStateChanged(evt);
            }
        });
        chkOleo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkOleoMouseClicked(evt);
            }
        });

        chkMed.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        chkMed.setForeground(new java.awt.Color(122, 122, 122));
        chkMed.setText("Medicamentos");
        chkMed.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 123, 123), 1, true));
        chkMed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkMed.setName("5"); // NOI18N
        chkMed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkMedStateChanged(evt);
            }
        });
        chkMed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkMedMouseClicked(evt);
            }
        });

        chkSofa.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        chkSofa.setForeground(new java.awt.Color(122, 122, 122));
        chkSofa.setText("Sofá");
        chkSofa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 123, 123), 1, true));
        chkSofa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkSofa.setName("4"); // NOI18N
        chkSofa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkSofaStateChanged(evt);
            }
        });
        chkSofa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkSofaMouseClicked(evt);
            }
        });
        chkSofa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSofaActionPerformed(evt);
            }
        });

        chkMicro.setFont(new java.awt.Font("Baloo 2", 0, 12)); // NOI18N
        chkMicro.setForeground(new java.awt.Color(122, 122, 122));
        chkMicro.setText("Micro-ondas");
        chkMicro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(123, 123, 123), 1, true));
        chkMicro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chkMicro.setName("7"); // NOI18N
        chkMicro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkMicroStateChanged(evt);
            }
        });
        chkMicro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkMicroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSmart, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkTablet, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkPilha, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOleo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMed, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkSofa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkMicro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(chkSmart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(chkTablet)
                .addGap(6, 6, 6)
                .addComponent(chkPilha)
                .addGap(12, 12, 12)
                .addComponent(chkOleo)
                .addGap(12, 12, 12)
                .addComponent(chkMed)
                .addGap(6, 6, 6)
                .addComponent(chkSofa)
                .addGap(6, 6, 6)
                .addComponent(chkMicro))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfc_compl, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfc_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfc_email, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_num, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_compl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cb_cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 60, 760, 420);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upxiii/imagens/Tela_inicial_cadastro.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 870, 570);

        setSize(new java.awt.Dimension(884, 597));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfc_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfc_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfc_nomeActionPerformed

    private void btn_enviar_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_cadastroActionPerformed
        // TODO add your handling code here:
//         for (int i = 0; i < Jarray.size(); i++) {
//                Object cat = Jarray.get(i);
//               
//            }
     
        try {

            Connection conn = BancoD.getConnection("meulixo", "root", "Finn20022122@");
            System.out.println("Nome: ");
            String nome = tfc_nome.getText();
            System.out.println("Email: ");
            String email = tfc_email.getText();
            System.out.println("Telefone: ");
            String telefone = tfc_tel.getText();
            System.out.println("Rua: ");
            String rua = tfc_rua.getText();
            System.out.println("Numero: ");
            String numero = tfc_num.getText();
            System.out.println("Bairro: ");
            String bairro = tfc_bairro.getText();
            System.out.println("Complemento: ");
            String complemento = tfc_compl.getText();
            System.out.println("CEP: ");
            String cep = tfc_cep.getText();
            System.out.println("Cidade: ");
            String cidade = tfc_cidade.getText();
            System.out.println("ID Local: ");
            System.out.println("Ativado: ");
            Boolean b=new Boolean(true);
//            System.out.println("Materiais Aceitos: ");
//            Jarray.toString();
//            JtipoDescarte.toString();
            int idLocal = 0;

         
//            Object cat = lista.getName();
            String sql = String.format(Locale.US,
                    "insert into local_descarte(email,nome,telefone,ativado)" + "values ('%s','%s','%s',%b);", email, nome, telefone,b
            );
            PreparedStatement stm = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            stm.executeUpdate();
//            System.out.println(stm);
            ResultSet rs = stm.getGeneratedKeys();
            
           
            if (rs.next()) {
                 idLocal = rs.getInt(1);
                System.out.println(idLocal);
                String sql2 = String.format(Locale.US,
                        "insert into endereco(id_local_descarte,logradouro,numero,bairro,complemento,cep,cidade)" + "values('%d','%s','%s','%s','%s','%s','%s');",
                        idLocal, rua, numero, bairro, complemento, cep, cidade);
                 BancoD.insert(conn, sql2);
                for (String checkboxiten : checkboxitens) {
                
                int idMaterial = Integer.parseInt(checkboxiten);
                String sql3 = String.format(Locale.US, 
                        "insert into material_local_descarte(id_material, id_local_descarte)" + "values('%d','%d');",
                        idMaterial,idLocal
                        );
                BancoD.insert(conn, sql3);
                }
                JOptionPane.showMessageDialog(null, "Usuario Cadastrado com Sucesso!");
               
            } else {
                JOptionPane.showMessageDialog(null, "Algo saiu Errado, Tente Novamente");
            }
               
            
//            String sql3 = String.format(
//                    "SELECT LCD.nome FROM MATERIAL MT INNER JOIN material_local_descarte MLD ON MT.id_material = MLD.id_material INNER JOIN local_descarte LCD ON MLD.ID_LOCAL_DESCARTE = LCD.id_local_descarte WHERE MT.id_material = '%d';",
//                    id_material );
//        Statement cmd = conn.createStatement();
//        ResultSet dados = cmd.executeQuery(sql3);
//        if(dados.next());
//              BancoD.insert(conn, sql3);
            
            
            

        } catch (Exception e) {
            System.out.print("Ocorreu um erro no sql"+ e.getMessage());
            e.printStackTrace();
             
           System.out.println("\nFalhou!");
        }
        


    }//GEN-LAST:event_btn_enviar_cadastroActionPerformed

    private void btn_voltar_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_cadastroActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            Local l = new Local();
            l.setVisible(true);
//            l.setLocation(null);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_voltar_cadastroActionPerformed
    
    
    private void cb_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_catActionPerformed
        // TODO add your handling code here:
         switch(cb_cat.getSelectedIndex()){
            case 1:
            chkSmart.setVisible(true);
            chkTablet.setVisible(true);

            break;
            case 2:
            chkPilha.setVisible(true);
            break;
            case 4:
            chkMed.setVisible(true);
            case 5:
            chkSofa.setVisible(true);
            break;
            case 6:
            chkOleo.setVisible(true);
            break;
            case 8:
            chkMicro.setVisible(true);
            break;
         }
    }//GEN-LAST:event_cb_catActionPerformed

    private void chkSmartStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSmartStateChanged
        // TODO add your handling code here:
       
        if(cb_cat.getSelectedItem().equals("Eletronico")){
            chkSmart.setVisible(true);
        }else if(!cb_cat.getSelectedItem().equals("Eletronico")){
            chkSmart.setVisible(false);
        }
    }//GEN-LAST:event_chkSmartStateChanged

    private void chkTabletStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkTabletStateChanged
        // TODO add your handling code here:
       
        if(cb_cat.getSelectedItem().equals("Eletronico")){
            chkTablet.setVisible(true);
        }else if(!cb_cat.getSelectedItem().equals("Eletronico")){
            chkTablet.setVisible(false);
        }
    }//GEN-LAST:event_chkTabletStateChanged

    private void chkPilhaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkPilhaStateChanged
        // TODO add your handling code here:
        
        if(cb_cat.getSelectedItem().equals("Pilhas e Baterias")){
            chkPilha.setVisible(true);
        }else if(!cb_cat.getSelectedItem().equals("Pilhas e Baterias")){
            chkPilha.setVisible(false);
        }
    }//GEN-LAST:event_chkPilhaStateChanged

    private void chkOleoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkOleoStateChanged
        // TODO add your handling code here:
        
        if(cb_cat.getSelectedItem().equals("Óleos")){
            chkOleo.setVisible(true);
        }else if(!cb_cat.getSelectedItem().equals("Óleos")){
            chkOleo.setVisible(false);
        }
    }//GEN-LAST:event_chkOleoStateChanged

    private void chkMedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkMedStateChanged
        // TODO add your handling code here:
        
        if(cb_cat.getSelectedItem().equals("Medicamentos")){
            chkMed.setVisible(true);
        }else if(!cb_cat.getSelectedItem().equals("Medicamentos")){
            chkMed.setVisible(false);
        }
    }//GEN-LAST:event_chkMedStateChanged

    private void chkSofaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkSofaStateChanged
        // TODO add your handling code here:
        
        if(cb_cat.getSelectedItem().equals("Móveis")){
            chkSofa.setVisible(true);
        }else if(!cb_cat.getSelectedItem().equals("Móveis")){
            chkSofa.setVisible(false);
        }
    }//GEN-LAST:event_chkSofaStateChanged

    private void chkSofaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSofaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSofaActionPerformed

    private void chkMicroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkMicroStateChanged
        // TODO add your handling code here:
        
        if(cb_cat.getSelectedItem().equals("Eletrodomésticos")){
            chkMicro.setVisible(true);
        }else if(!cb_cat.getSelectedItem().equals("Eletrodomésticos")){
            chkMicro.setVisible(false);
        }
    }//GEN-LAST:event_chkMicroStateChanged

    private void chkSmartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSmartActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_chkSmartActionPerformed

    private void chkSmartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkSmartMouseClicked
        // TODO add your handling code here:
         if(chkSmart.isSelected()){
            checkboxitens.add(chkSmart.getName());
            System.out.println(checkboxitens);
        }else{
            checkboxitens.remove(chkSmart.getName());
        }
    }//GEN-LAST:event_chkSmartMouseClicked

    private void chkMicroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkMicroMouseClicked
        // TODO add your handling code here:
        if(chkMicro.isSelected()){
            checkboxitens.add(chkMicro.getName());
        }else{
            checkboxitens.remove(chkMicro.getName());
        }
        
        
    }//GEN-LAST:event_chkMicroMouseClicked

    private void chkTabletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkTabletMouseClicked
        // TODO add your handling code here:
         if(chkTablet.isSelected()){
            checkboxitens.add(chkTablet.getName());
        }else{
            checkboxitens.remove(chkTablet.getName());
        }
        
        
    }//GEN-LAST:event_chkTabletMouseClicked

    private void chkPilhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkPilhaMouseClicked
        // TODO add your handling code here:
        if(chkPilha.isSelected()){
            checkboxitens.add(chkPilha.getName());
        }else{
            checkboxitens.remove(chkPilha.getName());
        }
        
        
    }//GEN-LAST:event_chkPilhaMouseClicked

    private void chkOleoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkOleoMouseClicked
        // TODO add your handling code here:
        if(chkOleo.isSelected()){
            checkboxitens.add(chkOleo.getName());
        }else{
            checkboxitens.remove(chkOleo.getName());
        }
        
        
        
    }//GEN-LAST:event_chkOleoMouseClicked

    private void chkMedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkMedMouseClicked
        // TODO add your handling code here:
        if(chkMed.isSelected()){
            checkboxitens.add(chkMed.getName());
        }else{
            checkboxitens.remove(chkMed.getName());
        }
        
        
        
    }//GEN-LAST:event_chkMedMouseClicked

    private void chkSofaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkSofaMouseClicked
        // TODO add your handling code here:
        if(chkSofa.isSelected()){
           checkboxitens.add(chkSofa.getName());
        }else{
            checkboxitens.remove(chkSofa.getName());
        }
        
        
        
    }//GEN-LAST:event_chkSofaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar_cadastro;
    private javax.swing.JButton btn_voltar_cadastro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_cat;
    private javax.swing.ButtonGroup check;
    private javax.swing.JCheckBox chkMed;
    private javax.swing.JCheckBox chkMicro;
    private javax.swing.JCheckBox chkOleo;
    private javax.swing.JCheckBox chkPilha;
    private javax.swing.JCheckBox chkSmart;
    private javax.swing.JCheckBox chkSofa;
    private javax.swing.JCheckBox chkTablet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfc_bairro;
    private javax.swing.JTextField tfc_cep;
    private javax.swing.JTextField tfc_cidade;
    private javax.swing.JTextField tfc_compl;
    private javax.swing.JTextField tfc_email;
    private javax.swing.JTextField tfc_nome;
    private javax.swing.JTextField tfc_num;
    private javax.swing.JTextField tfc_rua;
    private javax.swing.JTextField tfc_tel;
    // End of variables declaration//GEN-END:variables
}
