/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upxiii;

import java.sql.*;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JList;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author leogo
 */
public class Descarte extends javax.swing.JFrame {

    /**
     * Creates new form Descarte
     */
    public Descarte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_busca = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_voltar_local = new javax.swing.JButton();
        tf_pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_select = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quero Descartar");
        setResizable(false);
        getContentPane().setLayout(null);

        btn_busca.setBackground(new java.awt.Color(237, 228, 224));
        btn_busca.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_busca.setForeground(new java.awt.Color(102, 90, 72));
        btn_busca.setText("Buscar");
        btn_busca.setToolTipText("");
        btn_busca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_busca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_busca);
        btn_busca.setBounds(560, 70, 167, 35);

        jLabel2.setFont(new java.awt.Font("Baloo 2", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 90, 72));
        jLabel2.setText("Digite o material que deseja descartar:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 30, 670, 40);

        btn_voltar_local.setBackground(new java.awt.Color(237, 228, 224));
        btn_voltar_local.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_voltar_local.setForeground(new java.awt.Color(102, 90, 72));
        btn_voltar_local.setText("Voltar");
        btn_voltar_local.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 3, true));
        btn_voltar_local.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_localActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_local);
        btn_voltar_local.setBounds(60, 430, 150, 50);

        tf_pesquisa.setFont(new java.awt.Font("Baloo 2", 0, 14)); // NOI18N
        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_pesquisa);
        tf_pesquisa.setBounds(70, 70, 478, 35);

        ta_select.setColumns(20);
        ta_select.setRows(5);
        jScrollPane1.setViewportView(ta_select);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 130, 660, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upxiii/imagens/Tela Inicial.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(814, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaActionPerformed
        // TODO add your handling code here:
        try{
            Connection conn = BancoD.getConnection("meulixo", "root", "Finn20022122@");
            System.out.println("Pesquisa");
            String pesquisa = tf_pesquisa.getText();
            
            String sql = String.format(
                    "select  nome, email, telefone, logradouro, numero, bairro, complemento, cep, cidade from material m join material_local_descarte mld on mld.id_material = m.id_material join local_descarte ld on ld.id_local_descarte = mld.id_local_descarte join endereco e on e.id_local_descarte = ld.id_local_descarte where m.descricao = '%s';",
                    pesquisa);
            
            for(String linha: BancoD.list(conn, sql)){
                ta_select.append(linha);
            }
            
           
        }catch(Exception e){
            e.printStackTrace();
        }

        
    }//GEN-LAST:event_btn_buscaActionPerformed

    private void btn_voltar_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_localActionPerformed
        // TODO add your handling code here:
        this.dispose();
            
        try{
            TelaPrincipal tl = new TelaPrincipal();
           tl.setVisible(true);
//            tl.setLocation(null);
            
//            this.setVisible(false);
//            this.setLocation(null);
        
        }catch(Exception e){
            
        
        }
        
        
    }//GEN-LAST:event_btn_voltar_localActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
        // TODO add your handling code here:
        tf_pesquisa.getText().toLowerCase();
        
    }//GEN-LAST:event_tf_pesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Descarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Descarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Descarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Descarte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Descarte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_busca;
    private javax.swing.JButton btn_voltar_local;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_select;
    private javax.swing.JTextField tf_pesquisa;
    // End of variables declaration//GEN-END:variables
}
