/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upxiii;

import java.sql.*;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JList;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author leogo
 */
public class ExcluirLocal extends javax.swing.JFrame {

    /**
     * Creates new form ExcluirLocal
     */
    public ExcluirLocal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        btn_voltar_excluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfc_nome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        id_label = new javax.swing.JLabel();
        tfc_id = new javax.swing.JTextField();
        btn_id = new javax.swing.JButton();
        btn_excluir_cadastro = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Excluir Cadastro");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 90, 72));
        jLabel10.setText("Excluir Cadastro");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 10, 330, 40);

        btn_voltar_excluir.setBackground(new java.awt.Color(240, 240, 240));
        btn_voltar_excluir.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_voltar_excluir.setForeground(new java.awt.Color(122, 122, 122));
        btn_voltar_excluir.setText("Voltar");
        btn_voltar_excluir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        btn_voltar_excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_voltar_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltar_excluirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_voltar_excluir);
        btn_voltar_excluir.setBounds(210, 480, 166, 54);

        jPanel1.setBackground(new java.awt.Color(237, 250, 234));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(508, 771));

        jLabel1.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(122, 122, 122));
        jLabel1.setText("Nome");

        jLabel9.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 90, 72));
        jLabel9.setText("Dados Pessoais");

        tfc_nome.setForeground(new java.awt.Color(122, 122, 122));
        tfc_nome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));
        tfc_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfc_nomeActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(153, 153, 153));
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setOpaque(true);

        id_label.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        id_label.setForeground(new java.awt.Color(122, 122, 122));
        id_label.setText("Identificação");

        tfc_id.setForeground(new java.awt.Color(122, 122, 122));
        tfc_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));
        tfc_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfc_idActionPerformed(evt);
            }
        });

        btn_id.setBackground(new java.awt.Color(237, 228, 224));
        btn_id.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_id.setForeground(new java.awt.Color(159, 135, 114));
        btn_id.setText("Qual minha Identificação?");
        btn_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 4, true));
        btn_id.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfc_id, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(273, Short.MAX_VALUE))
            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_id, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id_label, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfc_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(172, 172, 172)
                .addComponent(btn_id, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 50, 760, 420);

        btn_excluir_cadastro.setBackground(new java.awt.Color(237, 228, 224));
        btn_excluir_cadastro.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_excluir_cadastro.setForeground(new java.awt.Color(122, 122, 122));
        btn_excluir_cadastro.setText("Excluir Cadastro");
        btn_excluir_cadastro.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 1, true));
        btn_excluir_cadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir_cadastro.setMaximumSize(new java.awt.Dimension(53, 32));
        btn_excluir_cadastro.setMinimumSize(new java.awt.Dimension(53, 32));
        btn_excluir_cadastro.setPreferredSize(new java.awt.Dimension(53, 32));
        btn_excluir_cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_cadastroActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir_cadastro);
        btn_excluir_cadastro.setBounds(470, 480, 166, 54);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upxiii/imagens/Tela_inicial_cadastro.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 870, 570);

        setSize(new java.awt.Dimension(884, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_voltar_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltar_excluirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try {
            Local l = new Local();
            l.setVisible(true);
            //           l.setLocation(null);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_voltar_excluirActionPerformed

    private void btn_excluir_cadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_cadastroActionPerformed
        // TODO add your handling code here:
//       DeleteDialog dd = new DeleteDialog(this,true);
//       dd.setLocationRelativeTo(null);
//       dd.setVisible(true);
        try {
            Connection conn = BancoD.getConnection("meulixo", "root", "Finn20022122@");
            System.out.println("Nome: ");
            String nome = tfc_nome.getText();
            System.out.println("Identificacao: ");
            int id = Integer.parseInt(tfc_id.getText());
           
       
             String sql2 = String.format(
                     "delete from material_local_descarte where id_local_descarte=%d;",
                     id
             );
             BancoD.insert(conn, sql2);
             String sql3 = String.format(
                     "delete from endereco where id_local_descarte=%d;",
                     id
             );
             BancoD.insert(conn, sql3);       
                     
                        
         String sql4 = String.format(
                    "delete from local_descarte where nome='%s';",
                 nome);
         BancoD.insert(conn, sql4);
         JOptionPane.showMessageDialog(null, "Usuario Deletado com Sucesso!");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Algo saiu Errado, Tente Novamente");
        }


    }//GEN-LAST:event_btn_excluir_cadastroActionPerformed

    private void tfc_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfc_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfc_nomeActionPerformed

    private void btn_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_idActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try{
            Identificacao id = new Identificacao();
            id.setVisible(true);

            //            this.setVisible(false);
            //            this.setLocation(null);

        }catch(Exception e){

        }

    }//GEN-LAST:event_btn_idActionPerformed

    private void tfc_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfc_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfc_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExcluirLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExcluirLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExcluirLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExcluirLocal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExcluirLocal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_excluir_cadastro;
    private javax.swing.JButton btn_id;
    private javax.swing.JButton btn_voltar_excluir;
    private javax.swing.JLabel id_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfc_id;
    private javax.swing.JTextField tfc_nome;
    // End of variables declaration//GEN-END:variables
}
