/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upxiii;

import java.sql.*;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.Locale;
import javax.swing.JList;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;

/**
 *
 * @author leogo
 */
public class Identificacao extends javax.swing.JFrame {

    /**
     * Creates new form Identificacao
     */
    public Identificacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfc_nomeid = new javax.swing.JTextField();
        tfc_emailid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_id_show = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_ident = new javax.swing.JTextArea();
        btn_id_voltar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(237, 250, 234));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 5, true));
        jPanel1.setPreferredSize(new java.awt.Dimension(508, 771));

        jLabel2.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(122, 122, 122));
        jLabel2.setText("Nome");

        jLabel3.setFont(new java.awt.Font("Inter", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(122, 122, 122));
        jLabel3.setText("Email");

        tfc_nomeid.setForeground(new java.awt.Color(122, 122, 122));
        tfc_nomeid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));
        tfc_nomeid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfc_nomeidActionPerformed(evt);
            }
        });

        tfc_emailid.setForeground(new java.awt.Color(122, 122, 122));
        tfc_emailid.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(122, 122, 122), 1, true));

        jLabel9.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 90, 72));
        jLabel9.setText("Dados Pessoais");

        btn_id_show.setBackground(new java.awt.Color(237, 228, 224));
        btn_id_show.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_id_show.setForeground(new java.awt.Color(159, 135, 114));
        btn_id_show.setText("Mostrar Identificação");
        btn_id_show.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 4, true));
        btn_id_show.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_id_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_id_showActionPerformed(evt);
            }
        });

        ta_ident.setColumns(20);
        ta_ident.setRows(5);
        jScrollPane1.setViewportView(ta_ident);

        btn_id_voltar.setBackground(new java.awt.Color(237, 228, 224));
        btn_id_voltar.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_id_voltar.setForeground(new java.awt.Color(159, 135, 114));
        btn_id_voltar.setText("Voltar");
        btn_id_voltar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 4, true));
        btn_id_voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_id_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_id_voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfc_emailid, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(tfc_nomeid)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_id_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btn_id_show, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_nomeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfc_emailid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(173, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_id_show, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_id_voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(52, 71, 760, 420);

        jLabel10.setFont(new java.awt.Font("Baloo 2", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 90, 72));
        jLabel10.setText("Identificação ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 10, 240, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upxiii/imagens/Tela_inicial_cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 870, 570);

        setSize(new java.awt.Dimension(884, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfc_nomeidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfc_nomeidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfc_nomeidActionPerformed

    private void btn_id_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_id_showActionPerformed
        // TODO add your handling code here:
       try{
            Connection conn = BancoD.getConnection("meulixo", "root", "Finn20022122@");
            System.out.println("Nome");
            String nome = tfc_nomeid.getText();
            System.out.println("Email");
            String email = tfc_emailid.getText();
            
            
            
            String sql2 = String.format(
                    "select id_local_descarte, nome, email from local_descarte where nome='%s' and email='%s';",
                    nome, email);
            
            Statement cmd = conn.createStatement();
            ResultSet dados = cmd.executeQuery(sql2);
            if(dados.next()){
            for(String line: BancoD.listNova(conn, sql2)){
                ta_ident.append(line);
            }
            }else{
            JOptionPane.showMessageDialog(null, "Algo deu Errado! Tente Novamente");
        }
           
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_id_showActionPerformed

    private void btn_id_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_id_voltarActionPerformed
        // TODO add your handling code here:
          this.dispose();
        try {
            ExcluirLocal el = new ExcluirLocal();
            el.setVisible(true);
//            l.setLocation(null);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_id_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Identificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Identificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Identificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Identificacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Identificacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_id_show;
    private javax.swing.JButton btn_id_voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_ident;
    private javax.swing.JTextField tfc_emailid;
    private javax.swing.JTextField tfc_nomeid;
    // End of variables declaration//GEN-END:variables
}
