/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upxiii;

/**
 *
 * @author leogo
 */
public class Local extends javax.swing.JFrame {

    /**
     * Creates new form Local
     */
    public Local() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btn_cadastro_local = new javax.swing.JButton();
        btn_atualizar_local = new javax.swing.JButton();
        btn_excluir_local = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sou um Local de Descarte");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_cadastro_local.setBackground(new java.awt.Color(237, 228, 224));
        btn_cadastro_local.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_cadastro_local.setForeground(new java.awt.Color(159, 135, 114));
        btn_cadastro_local.setText("Cadastrar Local de Descarte");
        btn_cadastro_local.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 4, true));
        btn_cadastro_local.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cadastro_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastro_localActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cadastro_local);
        btn_cadastro_local.setBounds(440, 134, 280, 60);

        btn_atualizar_local.setBackground(new java.awt.Color(237, 228, 224));
        btn_atualizar_local.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_atualizar_local.setForeground(new java.awt.Color(159, 135, 114));
        btn_atualizar_local.setText("Atualizar Dados");
        btn_atualizar_local.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 4, true));
        btn_atualizar_local.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_atualizar_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizar_localActionPerformed(evt);
            }
        });
        getContentPane().add(btn_atualizar_local);
        btn_atualizar_local.setBounds(440, 231, 280, 60);

        btn_excluir_local.setBackground(new java.awt.Color(237, 228, 224));
        btn_excluir_local.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_excluir_local.setForeground(new java.awt.Color(159, 135, 114));
        btn_excluir_local.setText("Excluir Cadastro");
        btn_excluir_local.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 4, true));
        btn_excluir_local.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_excluir_local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_excluir_localActionPerformed(evt);
            }
        });
        getContentPane().add(btn_excluir_local);
        btn_excluir_local.setBounds(440, 324, 280, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upxiii/imagens/Tela Inicial.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(814, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cadastro_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastro_localActionPerformed
        // TODO add your handling code here:
        this.dispose();
        try{
            CadastroLocal cl = new CadastroLocal();
            cl.setVisible(true);
            
//            this.setVisible(false);
//            this.setLocation(null);   
                
        }catch(Exception e){
            
        
        }
       
    }//GEN-LAST:event_btn_cadastro_localActionPerformed

    private void btn_excluir_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_excluir_localActionPerformed
        // TODO add your handling code here:
        try{
            ExcluirLocal el = new ExcluirLocal();
           el.setVisible(true);
            el.setLocation(null);
            this.setVisible(false);
            this.setLocation(null);
        }catch(Exception e){
            
        
        }this.dispose();
    }//GEN-LAST:event_btn_excluir_localActionPerformed

    private void btn_atualizar_localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizar_localActionPerformed
        // TODO add your handling code here:
        dispose();
        try{
            AtualizarLocal al = new AtualizarLocal();
            al.setVisible(true);
            al.setLocation(null);
//            this.setVisible(false);
//            this.setLocation(null); 
           
        }catch(Exception e){
            
        
        }
        
    }//GEN-LAST:event_btn_atualizar_localActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
            
        try{
            TelaPrincipal tl = new TelaPrincipal();
           tl.setVisible(true);
       }catch(Exception e){
            
        
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Local().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar_local;
    private javax.swing.JButton btn_cadastro_local;
    private javax.swing.JButton btn_excluir_local;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
