/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package upxiii;

/**
 *
 * @author leogo
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_tl_descarte = new javax.swing.JButton();
        btn_tl_cadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MeuLixo.com");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(null);

        btn_tl_descarte.setBackground(new java.awt.Color(237, 228, 224));
        btn_tl_descarte.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_tl_descarte.setForeground(new java.awt.Color(159, 135, 114));
        btn_tl_descarte.setText("Quero Descartar");
        btn_tl_descarte.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 3, true));
        btn_tl_descarte.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tl_descarte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tl_descarteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tl_descarte);
        btn_tl_descarte.setBounds(470, 210, 220, 60);

        btn_tl_cadastrar.setBackground(new java.awt.Color(237, 228, 224));
        btn_tl_cadastrar.setFont(new java.awt.Font("Baloo 2", 1, 18)); // NOI18N
        btn_tl_cadastrar.setForeground(new java.awt.Color(159, 135, 114));
        btn_tl_cadastrar.setText("Sou um Local de Descarte");
        btn_tl_cadastrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(159, 135, 114), 3, true));
        btn_tl_cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tl_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tl_cadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_tl_cadastrar);
        btn_tl_cadastrar.setBounds(470, 300, 220, 60);

        jLabel2.setFont(new java.awt.Font("Baloo 2", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 90, 72));
        jLabel2.setText("Meu Lixo . com");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(400, 70, 350, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upxiii/imagens/Tela Inicial.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 500);

        setSize(new java.awt.Dimension(814, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tl_descarteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tl_descarteActionPerformed
        // TODO add your handling code here:
        
           // this.setVisible(false);
        this.dispose();
        try{
            Descarte d = new Descarte();
            d.setVisible(true);
            d.setLocation(null);
            
            
            
        }catch(Exception e){
            
        
        }
        
//        this.setVisible(false);
        
    }//GEN-LAST:event_btn_tl_descarteActionPerformed

    private void btn_tl_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tl_cadastrarActionPerformed
        // TODO add your handling code here:
//        this.setVisible(false);
            this.dispose();
        try{
            //TelaPrincipal tl = new TelaPrincipal();
            Local l = new Local();
            l.setVisible(true);
            l.setLocation(null);
            //tl.setVisible(false);
           
        }catch(Exception e){
            
        
        }
        
            
    }//GEN-LAST:event_btn_tl_cadastrarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tl_cadastrar;
    private javax.swing.JButton btn_tl_descarte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
